###get all persons
GET http://localhost:3001/api/persons

###get info api
GET http://localhost:3001/info

###get person for ID
GET http://localhost:3001/api/persons/4

###Delete person
DELETE http://localhost:3001/api/persons/4

###Post person
POST http://localhost:3001/api/persons 
content-type: application/json

{
    "name": "juan rojas",
    "number": "1234"
}